name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Integration test
        uses: gonzalonaveira/gh-image-resizing@master
        with:
          DEBUG: "True"
          IMAGES_MAX_WIDTH: "1500"
          IMAGES_QUALITY: "90"
          IMAGES_FORMATS: "jpg, jpge, png"
          IMAGES_DIRECTORIES: "tests/path_1, tests/path_2"
          IMAGES_PREFIX: "prefix"
          IMAGES_SUFFIX: "suffix"

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.result }}" == "['prefixshould_resize_hatsuffix.png', 'prefixshould_resize_sky_2suffix.jpg', 'prefixshould_not_resize_umbrellasuffix.png']"
